---
#========================
# File darkServer.yml
#
# Description: Creates a dark server on the failover cluster
#
# Author: dRock Halsey
#========================

- name: PLAYBOOK | dark server
  hosts: "{{ variable_host }}"
  connection: local
  gather_facts: false
  roles:
  - newClusterVm
  tags:
  - spawn

- name: PLAYBOOK | dark server
  hosts: "{{ variable_host }}"
  gather_facts: false
  roles:
  - ubuntuSetup
  - ubuntuUpdate
  - ubuntuCifsClient