---
#========================
# File darkServer.yml
#
# Description: Creates a dark server on the failover cluster
#
# Author: dRock Halsey
#========================

- name: PLAYBOOK | Gather Facts
  hosts: windows

- name: PLAYBOOK | dark server
  hosts: testVM.DINOHEAD.NINJA
  connection: local
  gather_facts: false
  roles:
  - ubuntuServer