---
#========================
# File destroyClusterVm.yml
#
# Description: Destroys a VM on from the failover cluster
#
# Author: dRock Halsey
#========================

- name: PLAYBOOK | Seek and destroy a cluster VM
  hosts: "{{ variable_host }}"
  connection: local
  gather_facts: false
  tasks:

  - name: WIN_SHELL | Remove the VM from the cluster
    delegate_to: "{{ hostvar.hyperV.cluster }}"
    win_shell: |-
      if ( Get-ClusterResource -Cluster {{ hostvar.hyperV.cluster }} -Name "Virtual Machine {{ hostvar.sdn }}" -erroraction 'ignore' ) {
        Remove-ClusterGroup {{ hostvar.sdn }} -RemoveResources -cluster {{ hostvar.hyperV.cluster }} -Force }

  - name: WIN_SHELL | Stop the VM
    delegate_to: "{{ hostvar.hyperV.host }}"
    win_shell: |-
      if ( Get-VM -name {{ hostvar.sdn }} -erroraction 'ignore' ) {
        stop-vm {{ hostvar.sdn }} -Force }

  - name: WIN_SHELL | Remove the VM from the Hyper-V host
    delegate_to: "{{ hostvar.hyperV.host }}"
    win_shell: |-
      if ( Get-VM -name {{ hostvar.sdn }} -erroraction 'ignore' ) {
        remove-vm {{ hostvar.sdn }} -Force }

  - name: WIN_FILE | Remove VM from cluster storage
    delegate_to: "{{ hostvar.hyperV.host }}"
    win_file:
      path: "{{ hostvar.hyperV.storagePath }}\\{{ hostvar.sdn }}"
      state: absent

  - name: WIN_SHELL | Remove DNS entry
    delegate_to: "{{ groups.dc[0] }}"
    win_shell: |-
      if ( Get-DnsServerResourceRecord -Name "{{ hostvar.sdn }}" -ZoneName "{{ domain }}" -erroraction 'ignore' ) {
        Remove-DnsServerResourceRecord -ZoneName "{{ domain }}" -RRType "A" -Name "{{ hostvar.sdn }}" -Force }