---
#========================
# File newUbuntuServer.yml
#
# Description: Creates a VM on a Hyper-V host
#
# Author: dRock Halsey

- name: PLAYBOOK | newUbuntuServer - create a new Ubuntu Server on the Hyper-V host
  hosts: data.DINOHEAD.NINJA
  tasks:

  - name: WIN_FILE | Ensure Directories are present for new VM
    win_file:
      path: "{{ item }}"
      state: directory
    with_items:
      - C:\ClusterStorage\cluster-storage-01\vm\testVM
      - C:\ClusterStorage\cluster-storage-01\vm\testVM\Virtual Hard Disks

#  - name: WIN_COPY | Copy the VM template vhdx to the new directory
#    win_copy:
#      src: C:\ClusterStorage\cluster-storage-01\vhdx-templates\ubuntu-server-1604.vhdx
#      dest: C:\ClusterStorage\cluster-storage-01\vm\testVM\Virtual Hard Disks\disk-0.vhdx
#      remote_src: true

  - name: SCRIPT | Run powershell script newVM.ps1 to create new VM
    script: scripts/newVM.ps1