---
#========================
# File newUbuntuServer.yml
#
# Description: Creates a VM on a Hyper-V host
#
# Author: dRock Halsey

- name: PLAYBOOK | newUbuntuServer - create a new Ubuntu Server on the Hyper-V host
  hosts: data.DINOHEAD.NINJA
  tasks:

  - name: WIN_FILE | Ensure Directories are present for new VM
    win_file:
      path: "{{ item }}"
      state: directory
    with_items:
      - C:\ClusterStorage\cluster-storage-01\vm\testVM
      - C:\ClusterStorage\cluster-storage-01\vm\testVM\Virtual Hard Disks

#  - name: WIN_COPY | Copy the VM template vhdx to the new directory
#    win_copy:
#      src: C:\ClusterStorage\cluster-storage-01\vhdx-templates\ubuntu-server-1604.vhdx
#      dest: C:\ClusterStorage\cluster-storage-01\vm\testVM\Virtual Hard Disks\disk-0.vhdx
#      remote_src: true

  - name: WIN_COMMAND | Create VM in Hyper-V
    win_shell: if (!(Get-VM -name testVM -erroraction 'ignore')) { New-VM -Name "testVM" -ComputerName data -VHDPath "C:\ClusterStorage\cluster-storage-01\vm\testVM\Virtual Hard Disks\disk-0.vhdx" -Path "C:\ClusterStorage\cluster-storage-01\vm"}

  - name: WIN_COMMAND | Set Number of Proccessors
    win_shell: Set-VMProcessor testVM -Count 2

  - name: WIN_COMMAND | Set VM Memory
    win_shell: Set-VM -Name testVM -DynamicMemory -MemoryMaximumBytes 4GB -MemoryStartupBytes 1GB

  - name: WIN_COMMAND | Disconnect NIC
    win_shell: Disconnect-VMNetworkAdapter -VMName testVM

  - name: WIN_COMMAND | Start VM
    win_shell: start-vm testVM

  - name: SCRIPT | Run networking script to configure networking
    script: setHypervVmNetworking.ps1