---
#========================
# File darkServer.yml
#
# Description: Creates a dark server on the failover cluster
#
# Author: dRock Halsey
#========================

- name: Create the Cluster VM
  hosts: "{{ variable_host }}"
  connection: local
  gather_facts: false
  roles:
  - newClusterVm
  tags:
  - spawn

- name: Initial Ububtu Configuration
  hosts: "{{ variable_host }}"
  gather_facts: false
  roles:
  - ubuntuSetup
  - ubuntuUpdate
  - ubuntuCifsClient
  tags:
  - initalConfig

- name: Initial Ububtu Configuration
  hosts: "{{ variable_host }}"
  gather_facts: true
  roles:
  - ubuntuDesktop
  - transcoder
  tags:
  - transcoder
