---
#========================
# File tasks/main.yml
#
# Description:
#
# Author: Derek 'dRock' Halsey
#========================

- name: "APT_KEY | Ensure Google linux signing key present"
  become: true
  become_user: root
  apt_key:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    state: present

- name: "LINEINFILE | ensure Google chrome repo present in /etc/apt/sources.list.d"
  become: true
  become_user: root
  lineinfile:
    line: "{{ item.line }}"
    path: "{{ item.path }}"
    state: present
    create: true
  with_items:
  - { line: "deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main", path: "/etc/apt/sources.list.d/google-chrome.list" }
  - { line: "deb http://dl.google.com/linux/chrome-remote-desktop/deb stable main", path: "/etc/apt/sources.list.d/chromeos.list" }

- name: APT_REPOSITORY | Add PPA repository for makemkv and handbrake
  become: true
  become_user: root
  apt_repository:
    repo: "{{ item }}"
    update_cache: true
  with_items:
  - 'ppa:stebbins/handbrake-releases'
  - 'ppa:heyarje/makemkv-beta'

- name: "APT | update cache"
  become: true
  become_user: root
  apt:
    update_cache: yes

- name: "APT | Install packages"
  become: true
  become_user: root
  apt:
    name: "{{ item }}"
  with_items:
  - google-chrome-stable
  - handbrake-gtk
  - vlc
  - libdvd-pkg
  - browser-plugin-vlc
  - makemkv-bin
  - makemkv-oss
  - chrome-remote-desktop

- name: "SHELL | Configure libdvd"
  become: true
  become_user: root
  command: dpkg-reconfigure -f noninteractive libdvd-pkg

- name: "SHELL | Configure Launcher"
  command: dbus-launch gsettings set com.canonical.Unity.Launcher favorites "['application://org.gnome.Nautilus.desktop', 'application://gnome-terminal.desktop', 'application://unity-control-center.desktop', 'unity://running-apps', 'application://makemkv.desktop', 'application://google-chrome.desktop', 'application://ghb.desktop', 'unity://expo-icon', 'unity://devices']"

- name: "SHELL | Disable screen lock"
  command: dbus-launch gsettings set org.gnome.desktop.session idle-delay 0

- name: TEMPLATE | Template lightdm.conf to set autologon user
  become: true
  become_user: root
  template:
    src: lightdm.conf.j2
    dest: /etc/lightdm/lightdm.conf
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"

- name: TEMPLATE | Fix Chrome remote desktop session
  become: true
  become_user: root
  template:
    src: chrome-remote-desktop.j2
    dest: /opt/google/chrome-remote-desktop/chrome-remote-desktop
    owner: root
    group: root
    mode: "u=rwx,g=rx,o=rx"

- name: LINEINFILE | Fix resolution
  become: true
  become_user: root
  lineinfile:
    path: /etc/default/grub
    regexp: "GRUB_CMDLINE_LINUX_DEFAULT"
    line: "GRUB_CMDLINE_LINUX_DEFAULT=\"quiet splash video=hyperv_fb:1280x800\""
  register: transcoder_resolution

- name: COMMAND | Update Grub
  become: true
  become_user: root
  command: update-grub
  when: transcoder_resolution.changed

- name: SHELL | reboot the system when resolution fix was applied
  become: true
  become_user: root
  shell: sleep 2 && shutdown -r now "Ansible updates triggered"
  async: 1
  poll: 0
  when: transcoder_resolution.changed

- name: WAIT_FOR | Wait for ssh to resume
  local_action:
    module: wait_for
    port: 22
    host: "{{ transcoder.fqdn }}"
    delay: 30
    timeout: 400
