---
#========================
# File defaults/main.yml
#
# Description: default variables for role
#
# Author: Derek 'dRock' Halsey
#========================

linuxSetup:
  user:
    name: "{{ ansible_user }}"
    password: "{{ vault.password.text }}"

  ssh:
    public: "{{ vault.ssh.public }}"
    private: "{{ vault.ssh.private }}"
    authorizedKeys: "{{ vault.ssh.authorizedKeys }}"

  sdn: "{{ hostvar.sdn }}"
  fqdn: "{{ hostvar.fqdn }}"
  ip: "{{ hostvar.network.ip }}"
  becomePass: "{{ vault.password.text }}"