---
#========================
# File defaults/main.yml
#
# Description: default variables for role
#
# Author: Derek 'dRock' Halsey
#========================
transcoder:
  user: "{{ ansible_user }}"
  fqdn: "{{ hostvar.fqdn }}"