---
#========================
# File defaults/main.yml
#
# Description: default variables for role
#
# Author: Derek 'dRock' Halsey
#========================

newClusterVm:
  fqdn: "{{ hostvar.fqdn }}"
  sdn: "{{ hostvar.sdn }}"
  processors: "{{ hostvar.processors }}"
  node: "{{ hostvar.node }}"
  memory:
    type: "{{ hostvar.memory.type }}"
    min: "{{ hostvar.memory.min }}"
    max: "{{ hostvar.memory.max }}"
  network:
    vSwitch: "{{ hostvar.network.vSwitch }}"
    ip: "{{ hostvar.network.ip }}"
    subnet: "{{ hostvar.network.subnet }}"
    dns: "{{ hostvar.network.dns }}"
    gateway: "{{ hostvar.network.gateway }}"
  hyperV:
    host: "{{ groups.hyper_v[0] }}"
    cluster: "{{ groups.hyper_v_cluster[0] }}"
    storagePath: "{{ hyperV.storagePath }}"
    vhdxTemplate: "{{ hostvar.vhdxTemplate }}"
  dnsServer: "{{ groups.dc[0] }}"

# The Add-ClusterVirtualMachineRole powershell comandlet seems to be broken
# I've added this variable to turn off clustering for now
# TODO figure out how to fix this
  cluster: false