---
#========================
# File defaults/main.yml
#
# Description: default variables for role
#
# Author: Derek 'dRock' Halsey
#========================

ubuntuUpdate:
  fqdn: "{{ hostvar.fqdn }}"